name: Update contribution graph

on:
  # 1. Schedule: runs every day at midnight UTC
  schedule:
    - cron: '0 0 * * *'
  # 2. Manual trigger: you can click “Run workflow” in GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate activity graph
        uses: ashutosh00710/github-readme-activity-graph@v2

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add --force graph.svg
          git commit -m "chore: refresh activity graph" || echo "No changes to commit"
          git push
